apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: yemjoy
build:
  artifacts:
    - image: yemjoy/comments
      context: comments
      docker:
        dockerfile: Dockerfile
    - image: yemjoy/event-bus
      context: eventbus
      docker:
        dockerfile: Dockerfile
    - image: yemjoy/posts
      context: posts
      docker:
        dockerfile: Dockerfile
    - image: yemjoy/query
      context: query
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - infra/dev/comments-deployment.yaml
    - infra/dev/comments-service.yaml
    - infra/dev/event-bus-deployment.yaml
    - infra/dev/event-bus-service.yaml
    - infra/dev/ingress-service.yaml
    - infra/dev/posts-deployment.yaml
    - infra/dev/posts-service.yaml
    - infra/dev/posts.yaml
    - infra/dev/query-deployment.yaml
    - infra/dev/query-service.yaml
